FROM python:3.10-slim
WORKDIR /workspace
RUN apt-get update && \
    apt-get install --no-install-recommends -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /root/.cache
COPY requirements.txt /workspace/
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir gradio loguru
COPY app.py /workspace/
EXPOSE 49800
CMD ["python", "app.py"]